export const INPUT_NUMBER_DAYS = "INPUT_NUMBER_DAYS";
export const SELECT_FROM_DATA = "SELECT_FROM_DATA";
export const DELETE_FROM_DATA = "DELETE_FROM_DATA";
export const SELECT_BEFORE_DATA = "SELECT_BEFORE_DATA";
export const DELETE_BEFORE_DATA = "DELETE_BEFORE_DATA";
